scripts/unifdef: avoid constexpr keyword
Starting with c23, 'constexpr' is a keyword in C like in C++ and cannot
be used as an identifier:

scripts/unifdef.c:206:25: error: 'constexpr' can only be used in variable declarations
  206 | static bool             constexpr;              /* constant #if expression */
      |                         ^
kernel/oneplus/sm8550/scripts/unifdef.c:880:13: error: expected identifier or '('
  880 |                 constexpr = false;
      |                           ^
kernel/oneplus/sm8550/scripts/unifdef.c:898:13: error: expected identifier or '('
  898 |                 constexpr = false;
      |                           ^
kernel/oneplus/sm8550/scripts/unifdef.c:958:12: error: expected identifier or '('
  958 |         constexpr = killconsts ? false : true;
      |                   ^
kernel/oneplus/sm8550/scripts/unifdef.c:961:10: error: expected expression
  961 |         return (constexpr ? LT_IF : ret == LT_ERROR ? LT_IF : ret);
      |                 ^

Rename this instance to allow changing to C23 at some point in the future.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Reviewed-By: Tony Finch <dot@dotat.at>
Reviewed-by: Nicolas Schier <nicolas@fjasle.eu>
Signed-off-by: Masahiro Yamada <masahiroy@kernel.org>